### ISSUE TITLE
[Suggestion] The posibility to use the addon with multiconnect

### ISSUE THREAD

**Issue by Anldernx** [AntiCope/meteor-rejects#107]
### Describe the feature

Simply a way to use this addon in older versions of minecraft

**Comment by C10udburst** [comment]
<img src="https://cdn.discordapp.com/emojis/786145287910981663.webp?size=64&quality=lossless" width="64px" />

there's nothing stopping you from using it with multiconnect

**Comment by Anldernx** [comment]
i knew but somethinks like new chunks doesnt work while using muticonnect on older versions
