### ISSUE TITLE
[Suggestion] 1.18.1 support until other mods update to 1.18.2

### ISSUE THREAD

**Issue by fishiewishie** [AntiCope/meteor-rejects#110]
### Describe the feature

i use multiconnect to connect to other versions but it hasnt been updated to 1.18.2 yet and I'm unable to use meteor rejects on 1.18.1 is there any way to get an older version of rejects until multiconnect updates?

**Comment by C10udburst** [comment]
sure, i have made a [1.18.1 release](https://github.com/AntiCope/meteor-rejects/releases/tag/last-1.18.1)

**Comment by fishiewishie** [comment]
thanks for the help, I'm not getting the version error anymore but the game crashes at launch here's the report:
[crash-2022-03-03_14.04.08-client.txt](https://github.com/AntiCope/meteor-rejects/files/8180402/crash-2022-03-03_14.04.08-client.txt)

I also tried the new 1.18.2 version to see if it would work in a different instance and i got a different error (both versions work with meteor client if i don't have rejects installed):
https://paste.ee/p/2rhHC

**Comment by C10udburst** [comment]
> thanks for the help, I'm not getting the version error anymore but the game crashes at launch here's the report:
> [crash-2022-03-03_14.04.08-client.txt](https://github.com/AntiCope/meteor-rejects/files/8180402/crash-2022-03-03_14.04.08-client.txt)

you need to use [this devbuild](https://meteorclient.com/download?devBuild=1435)

**Comment by fishiewishie** [comment]
> > thanks for the help, I'm not getting the version error anymore but the game crashes at launch here's the report:
> > [crash-2022-03-03_14.04.08-client.txt](https://github.com/AntiCope/meteor-rejects/files/8180402/crash-2022-03-03_14.04.08-client.txt)
> 
> you need to use [this devbuild](https://meteorclient.com/download?devBuild=1435)

thanks this one worked
