### ISSUE TITLE
.seed works great but .locate locates wrong positions[Bug] 

### ISSUE THREAD

**Issue by procrafter820** [AntiCope/meteor-rejects#111]
### Describe the bug

.seed works great but .locate locates wrong positions

### Steps to reproduce

```plaintext
1.First open creative singleplayer with cheats enabled
2.Type /seed and .seed both are exactly same
3.then try .locate buried_treasure and /locate buried_treasure ........... both are different positions
...
```

### Operating System

Windows

### Rejects Version

1.18.1

### Meteor Version

0.4.8

### Minecraft Version

1.18.1

### Other mods

```plaintext
1.Coderx_shulker_dupe
2.
3.
...
```

**Comment by C10udburst** [comment]
well it doesn't matter of the command output is the same, it may have just found a different one.

could you actually tp there and check if there actually is a structure there?

**Comment by procrafter820** [comment]
No it is not there, I checked 9 times

**Comment by C10udburst** [comment]
missclick

**Comment by C10udburst** [comment]
ok I can reproduce this bug. Although nether and end work fine

**Comment by procrafter820** [comment]
> ok I can reproduce this bug.
> 
> it seems to be caused by the fact, that [mcbiome](https://github.com/SeedFinding/mc_biome_java) library is not updated to 1.18.

So can you make it without using that library(i mean alternative) ?

**Comment by C10udburst** [comment]
for now i have made it so it will use the backup methods while in 1.18 in overworld

**Comment by procrafter820** [comment]
ok
