### ISSUE TITLE
[Bug] Oresim needs a minecraft world version selector option in order to find the ores. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [AntiCope/meteor-rejects#112]
### Describe the bug

#Bug
Whenever im on old worlds of minecraft like 1.17, 1.16, or 1.18.1, Oresim does not locate the ores correctly. 

#Solution
In order to get around this, there needs to be in option in Oresim to select the world version in order to find the ores correctly. 

#More Information
-On the Atomic Client, you got the option to select the world version in order to help you locate to ores from old world seeds which simulate old worlds on old versions. 
![image](https://user-images.githubusercontent.com/62456796/158227230-447ed653-bad2-480a-8331-5320ecc3fbd4.png)

-On Meteor Rejects, you don't have that option and that option is very important. 
![image](https://user-images.githubusercontent.com/62456796/158227464-fb50e3cb-f3a3-486b-8759-1935b904d3dc.png)

### Steps to reproduce

```plaintext
1. Download the necessary mods. (SeedcrackerX, Meteor Client, Meteor Rejects)
2. Port an old world from 1.17 or 1.18.1 to your latest version of minecraft.
3. Grab the seed using seedcracker or a command. 
4. Turn on Oresim and try to find any ore like iron or coal.
5. Notice the bug that there are no ores in the highlighted location
...
```

### Operating System

Windows

### Rejects Version

meteor-rejects-addon-0.2.jar

### Meteor Version

meteor-client-0.4.8.jar

### Minecraft Version

1.18.2

### Other mods

```plaintext
No other mods except the 3 i mentioned cause i was using these for testing. 

1. SeedcrackerX
2. Meteor Client
3. Meteor Rejects
```

**Comment by C10udburst** [comment]
you can set the seed version `.seed <seed> <version>`
