### ISSUE TITLE
[Suggestion] Update to 1.19

### ISSUE THREAD

**Issue by MonkeySaint** [AntiCope/meteor-rejects#123]
### Describe the feature

Made this just for the pull request

**Comment by Funtimes909** [comment]
I am also asking for this

**Comment by MonkeySaint** [comment]
> I am also asking for this

I updated it I made this just to put a pull request.
https://github.com/MonkeySaint/meteor-rejects
That's my update if you want it.

**Comment by Funtimes909** [comment]
![image](https://user-images.githubusercontent.com/68979259/173162339-42c1e9d3-1ef1-42ef-ab57-e5e8cb352384.png)
Either or code does not work or I am incredibly stupid and do not know how github works

**Comment by MonkeySaint** [comment]
> ![image](https://user-images.githubusercontent.com/68979259/173162339-42c1e9d3-1ef1-42ef-ab57-e5e8cb352384.png)
> Either your code does not work or I am incredibly stupid and do not know how github works

You need to have meteor in your local maven. Just download the jar from the releases tab.

**Comment by MonkeySaint** [comment]
> ![image](https://user-images.githubusercontent.com/68979259/173162339-42c1e9d3-1ef1-42ef-ab57-e5e8cb352384.png)
> Either your code does not work or I am incredibly stupid and do not know how github works

https://github.com/MonkeySaint/meteor-rejects/releases/tag/latest-1.19

**Comment by C10udburst** [comment]
fixed by #124
