### ISSUE TITLE
[Bug] Game hangs when sleeping

### ISSUE THREAD

**Issue by maxjiang2021** [AntiCope/meteor-rejects#136]
### Describe the bug

The game hangs when you sleep with meteor rejects.

### Crashlog

(None, the game only hangs)

### Steps to reproduce

1. Install Meteor Client and Meteor Rejects
2. Go into a game
3. Sleep (not set respawn)

### Operating System

Linux

### Addon Version

0339975

### Meteor Version

0.5.0-1516

### Minecraft Version

1.19 fabric 0.14.8

### Other mods

```plaintext
1. Fabric API
```

**Comment by explasion** [comment]
Update to the latest 1.19 beta of Meteor. the link can be found in the official discord.

**Comment by ThebestkillerTBK** [comment]
cannot reproduce in latest
