### ISSUE TITLE
[Bug] Autocraft does not work.

### ISSUE THREAD

**Issue by Z3r0ut** [AntiCope/meteor-rejects#138]
### Describe the bug

I have all materials in my inventory, i have activated the module and added the things i want it to craft into the list but nothing happens.

### Crashlog

No crash.

### Steps to reproduce

1. Try to use the Autocraft module.

### Operating System

Windows

### Addon Version

0.2

### Meteor Version

0.5.0-1536

### Minecraft Version

1.19

### Other mods

```plaintext
1.
2.
3.
...
```

**Comment by TaxEvasiqn** [comment]
Step 2) right click on crafting table

**Comment by Z3r0ut** [comment]
> Step 2) right click on crafting table

obviously. How else should autocraft work? i didnt thought about mentioning cause i thought that is obvious.

**Comment by RegalAether** [comment]
you also have to open the recipe book, if that doesn't fix it idfk

**Comment by Z3r0ut** [comment]
> you also have to open the recipe book, if that doesn't fix it idfk

Bruh who thinks about to use the recipe book? yeah now it works.. Thanks.

**Comment by ShayBox** [comment]
This should really be added to the description, and mods that modify the recipe book like EMI break this functionality.
