### ISSUE TITLE
Game crashes when I try to open game 

### ISSUE THREAD

**Issue by 60YzArC** [AntiCope/meteor-rejects#140]
### Describe the bug

Its outdated so yh.

### Crashlog

its outdated

### Steps to reproduce

1.open mc 
2.it crashes
3. cry
...

### Addon Version

Latest version

### Meteor Version

Latest version

### Minecraft Version

Latest version

### Other mods

```plaintext
1.I tried it with none 
2.
3.
...
```

**Comment by C10udburst** [comment]
yeah, duplicate of #139
