### ISSUE TITLE
[CRASH] minecraft crashes when using meteor rejects with meteor 

### ISSUE THREAD

**Issue by Cronge** [AntiCope/meteor-rejects#144]
### Describe the bug

When using meteor rejects(with meteor client), Minecraft crashes on launch(also crashes with addons like these:  _Meteor Plus_, _Meteor tweaks_, _Meteor rejects_)but doesn't crash when I stop using them(using the Crash addon doesn't make MC crash)

I wonder why🤔..

### Crashlog

Crashlog:
[crash-2022-07-28_15.30.34-client.txt](https://github.com/AntiCope/meteor-rejects/files/9206663/crash-2022-07-28_15.30.34-client.txt)

latest.log
[latest.log](https://github.com/AntiCope/meteor-rejects/files/9206664/latest.log)

### Steps to reproduce

1. Get _Meteor Plus_, _Meteor Tweaks_ and _Meteor rejects_ . You can get them [here](https://anticope.ml/addons/?)
2. Use any of the addons specified(you can use them one by one)
3. When launching Minecraft with this, it should crash

### Operating System

_Windows 10 21H2 Build 19044.1826_

### Addon Version

36bc339e74cf8ba678f0fa8ff0674181e4cf1181 METEOR REJECTS 0.2-1.19

### Meteor Version

0.5.0-1566

### Minecraft Version

1.19

### Other mods

(23 mods)

[AppleSkin2.4.0+mc1.19(fabric)](https://modrinth.com/mod/appleskin)
[Blur 2.6.0-1.19(fabric)](https://modrinth.com/mod/blur-fabric)
[Dynamic FPS 2.2.0-1.19(fabric)](https://modrinth.com/mod/dynamic-fps)
[Fabric API 0.58.0+1.19](https://modrinth.com/mods?g=categories%3Afabric)
[Fabric Language Kotlin 1.8.1+kotlin.1.7.0](https://modrinth.com/mod/fabric-language-kotlin)
[Forget Me Chunk 1.0.4-1.18X-1.19X](https://modrinth.com/mod/forgetmechunk)

However, Forget Me Chunk **causes a memory leak**, this memory leak is reset by changing dimension or leaving the server/world.

[Indium 1.0.6+mc1.19](https://modrinth.com/mod/indium)
[Krypton 0.2.0-1.19(fabric)](https://modrinth.com/mod/krypton)
[LambDynamicLights 2.1.2+1.19(fabric)](https://modrinth.com/mod/lambdynamiclights)
[LazyDFU 0.1.3-1.19(fabric)](https://modrinth.com/mod/lazydfu)
[Lithium 0.8.1-1.19(fabric)](https://modrinth.com/mod/lithium)
[Memory Leak Fix 1.19-0.5.4(fabric)](https://modrinth.com/mod/memoryleakfix)
[Meteor Client 0.5.0dev-1566 ](https://meteorclient.com)
[Mod Menu 4.0.4-1.19](https://modrinth.com/mod/modmenu)
[perspektive 1.1.0-1.19](https://modrinth.com/mod/perspektive)
[Reese's Sodium Options 1.4.4+mc1.19-build.47](https://modrinth.com/mod/reeses-sodium-options)
[Sodium 0.4.2+build.96-1.19](https://modrinth.com/mod/sodium)
[Sodium Extra 0.4.6+mc1.19-build.47](https://modrinth.com/mod/sodium-extra)
[Starlight 1.1.1+fabric.ae22326-1.19](https://modrinth.com/mod/starlight)
[Very Many Players(VMP) 0.2.0+beta.6.28](https://modrinth.com/mod/vmp-fabric)
[Zoomify 1.7.1-1.19](https://modrinth.com/mod/zoomify)

**Comment by RegalAether** [comment]
the issue is not with meteor or anything related, it's that you're using a mojang account, migrate your account. also meteor  plus and meteor tweaks are outdated and broken currently

**Comment by Cronge** [comment]
> 

I use a Microsoft account..

**Comment by Cronge** [comment]
> the issue is not with meteor or anything related, it's that you're using a mojang account, migrate your account. also meteor tweaks is outdated and broken currently

Minecraft crashes when I use Meteor Rejects and MeteorPlus although not Meteor Crash Addon..

**Comment by RegalAether** [comment]
both of those work fine for everyone else i've talked to so it's a different issue

**Comment by Cronge** [comment]
yeah..

**Comment by Cronge** [comment]
It's weird though..
Minecraft crashing..

**Comment by Cronge** [comment]
Also I am using [MultiMC](https://multimc.org), this allows me to disable mods(not remove them but _disable_)so there _might_ be some disabled mods showing up in the logs.

**Comment by C10udburst** [comment]
does it launch without any mods?

**Comment by C10udburst** [comment]
one of your addons is outdated

**Comment by Cronge** [comment]
> one of your addons is outdated

Which one?

**Comment by RegalAether** [comment]
their crash log only had meteor and meteor rejects

**Comment by Cronge** [comment]
> 

Sure I'll try that.

**Comment by C10udburst** [comment]
update meteor and all your addons

**Comment by RegalAether** [comment]
they're using latest meteor and seems to be latest rejects in the latest.log

**Comment by Cronge** [comment]
> 

👍

**Comment by C10udburst** [comment]
> they're using latest meteor and seems to be latest rejects in the latest.log

im looking at the crash log, latest.log doesnt have anything useful

**Comment by Cronge** [comment]
> update meteor and all your addons

I'm pretty sure I'm using the latest versions.

**Comment by RegalAether** [comment]
redownload rejects, that seems to be the issue

**Comment by Cronge** [comment]
> redownload rejects, that seems to be the issue

Okay.

**Comment by Cronge** [comment]
> redownload rejects, that seems to be the issue

YES! It worked.
I'm going to try it with other addons.

**Comment by Cronge** [comment]
> redownload rejects, that seems to be the issue

It's fixed!
I didn't know all it took was just a simple redownload.😂
Thank you guys!❤️
