### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by exually** [AntiCope/meteor-rejects#147]
### Describe the bug

My game crashes when I try to enable a module on meteor-rejects (1.19)
This started happening one day before I installed meteor-rejects. Minecraft would crash everytime I went to spawn (on an anarchy server), but only when I was running the game with meteor installed.

### Crashlog

[crash-2022-08-08_10.50.34-client.txt](https://github.com/AntiCope/meteor-rejects/files/9280435/crash-2022-08-08_10.50.34-client.txt)

### Steps to reproduce

1. open minecraft launcher
2. launch fabric loader 1.19 with meteor client and meteor-rejects installed
3. enable or disable a meteor-rejects module

### Operating System

Windows

### Meteor Version

Release 0.5.0, 1.19

### Minecraft Version

1.19

### Other mods

```plaintext
meteor is running on fabric loader 1.19
```

**Comment by C10udburst** [comment]
you should use the 1.19.1 devbuild

**Comment by exually** [comment]
> you should use the 1.19.1 devbuild

That worked but the problem is that the server I'm playing on is still on 1.19. If there is no other solution to this bug, I'll just wait for the server to update.

**Comment by C10udburst** [comment]
use multiconnect and/or viaversion
