### ISSUE TITLE
[Bug] missing 1.19 in .seed

### ISSUE THREAD

**Issue by phvkuhkk** [AntiCope/meteor-rejects#152]
### Describe the bug

when you insert a seed with .seed (seed) (version) it only goes up to 1.18.2 even in 1.19

### Crashlog

no crash

### Steps to reproduce

1. .seed (seed) (version)

### Addon Version

1.19 build

### Meteor Version

0.5.0

### Minecraft Version

1.19

**Comment by I-Got-You-Dead** [comment]
Omfg they are the same

**Comment by phvkuhkk** [comment]
> Omfg they are the same

how is 1.18.2 and 1.19 the same?

**Comment by C10udburst** [comment]
the ore gen is pretty much the same
