### ISSUE TITLE
[Bug] .seed not working correctly

### ISSUE THREAD

**Issue by phvkuhkk** [AntiCope/meteor-rejects#153]
### Describe the bug

when i type .seed it just says "No seed for current world saved." (on minehut)

### Crashlog

.

### Steps to reproduce

1. type .seed
2.
3.
...

### Operating System

Windows

### Addon Version

1.19 build

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Other mods

```plaintext
1.
2.
3.
...
```

**Comment by C10udburst** [comment]
To use Ore Sim or `.locate` seed features you need to firstly set the seed using `.seed <seed> <version>` command.
Rejects doesn't have any seed cracking features, but you can use it with SeedCrackerX. You can download it here:
https://github.com/19MisterX98/SeedcrackerX
You can also visit SeedcrackerX discord server if you have any issues:
https://discord.gg/JRmHzqQYfp
