### ISSUE TITLE
[Suggestion] Text Replacer

### ISSUE THREAD

**Issue by GoofyBoi420** [AntiCope/meteor-rejects#163]
### Describe the feature

so what it does is it changes your chat example when you type fro (for) then in chat it comes as for. its for spelling mistakes and other things like :skul: would be 💀 in chat

the end 😄

**Comment by C10udburst** [comment]
use orion for that

**Comment by GoofyBoi420** [comment]
orion not virus??

**Comment by I-Got-You-Dead** [comment]
If you really want, I can just paste from my client into a pr ig

**Comment by GoofyBoi420** [comment]
so its not virus?

**Comment by I-Got-You-Dead** [comment]
No 🙄

**Comment by GoofyBoi420** [comment]
vaaaairus?
