### ISSUE TITLE
[Suggestion] Customizable Auto EZ and Egap Finder

### ISSUE THREAD

**Issue by Epik123** [AntiCope/meteor-rejects#17]
- [x] Customizable Auto EZ

and
- [ ] EGap Finder

**Comment by C10udburst** [comment]
> Bedaura (auto places and breaks beds near ur enemy's good for nether pvp

Already in meteor

> auto bedtrap just bedtrap people lol

literally already in this module

> Anti respawn point lose for both beds and anchors

also already in this module. Did you even read the [readme](https://github.com/C10udburst/meteor-rejects#readme), let alone launch this addon?

> Anti tnt aura (auto breaks all tnt within a certain range)

I think this can be done by selecting tnt in nuker

> Auto totem bypass for matrix anticheat

Autototem is a meteor feature, so ask them

> Custom fast use so u can choose witch items are affected etc

Fast use is a meteor feature, so ask them

**Comment by Epik123** [comment]
> > Bedaura (auto places and breaks beds near ur enemy's good for nether pvp
> 
> Already in meteor
> 
> > auto bedtrap just bedtrap people lol
> 
> literally already in this module
> 
> > Anti ghost block
> 
> literally already in this module
> 
> > Anti respawn point lose for both beds and anchors
> 
> also already in this module. Did you even read the [readme](https://github.com/C10udburst/meteor-rejects#readme), let alone launch this addon?
> 
> > Anti tnt aura (auto breaks all tnt within a certain range)
> 
> I think this can be done by selecting tnt in nuker
> 
> > Auto totem bypass for matrix anticheat
> 
> Autototem is a meteor feature, so ask them
> 
> > Custom fast use so u can choose witch items are affected etc
> 
> Fast use is a meteor feature, so ask them

Sad :( yeah I realized about a minute after this post

**Comment by C10udburst** [comment]
> Sad :( yeah I realized about a minute after this post

🤡

**Comment by Epik123** [comment]
> > Sad :( yeah I realized about a minute after this post
> 
> 🤡

Idk man seems kinda sus to me

**Comment by StormyBytes** [comment]
Edited this to make it more useful and clear

**Comment by Epik123** [comment]
e
