### ISSUE TITLE
[Suggestion] auto steal

### ISSUE THREAD

**Issue by easyloo** [AntiCope/meteor-rejects#175]
### Describe the feature

idk why meteor devs wont do it

**Comment by I-Got-You-Dead** [comment]
Already in meteor 🤡🤡🤡

**Comment by easyloo** [comment]
doesnt work tho

**Comment by I-Got-You-Dead** [comment]
Then either cope harder or fix it yourself

**Comment by C10udburst** [comment]
> Already in meteor 🤡🤡🤡

^^^^
