### ISSUE TITLE
[Suggestion] Console

### ISSUE THREAD

**Issue by ProfKambing** [AntiCope/meteor-rejects#176]
### Describe the feature

so i figured out how to run meteor on feather client. but now the commands arent working, so can you create a console to input commands? it would be dope if you add it.

**Comment by RacoonDog** [comment]
Feather client is explicitly set as incompatible for a reason

**Comment by I-Got-You-Dead** [comment]
Don’t use a skidded client

**Comment by TaxEvasiqn** [comment]
cocknballs

**Comment by I-Got-You-Dead** [comment]
> cocknballs

(real)
