### ISSUE TITLE
[Bug] OreSim does not work (minecraft server version 1.18.2)

### ISSUE THREAD

**Issue by Aholicknight** [AntiCope/meteor-rejects#194]
### Describe the bug

After cracking the world seed with SeedCrackerX it does not simulate ores correctly. 

![image](https://user-images.githubusercontent.com/7843719/208782790-cfbc5344-1b2b-491b-a279-12dfd6e8221b.png) 

The world seed is `3480508649305364` and on version 1.18.2, but when I try to use Ore Sim to find all the diamonds (they have some sort of anti x-ray plugin) it does not show them correctly. These are my [ore sim settings](https://i.imgur.com/lYze4VJ.png) (everything is set to default), and I have also recorded a video of the problem which can be seen here: 

https://user-images.githubusercontent.com/7843719/208788147-4e7e9cae-ac2e-4833-a6ad-5765e132bbcf.mp4

### Crashlog

No crashlog

### Steps to reproduce

1. Create a new world with the world seed `3480508649305364`
2. Enable Ore Sim and check for diamonds. 
3. When you get close to a diamond ore, you will see it is not simulating ore correctly.

### Operating System

Windows

### Addon Version

[6493377](https://github.com/AntiCope/meteor-rejects/commit/64933773a7a4f2fc393ca1d21003905e9755b88a)

### Meteor Version

v0.5.1 1624

### Minecraft Version

1.19.2 (server version is 1.18.2)

### Other mods

```plaintext
1. meteor-crash-addon-0.6.jar
2. meteor-rejects-addon-0.2.jar
3. meteorist.jar
4. multiconnect-1.6-beta.23.jar
5. reaper-0.1.jar
6. seedcrackerX-2.13.jar
7. sodium-fabric-mc1.19.2-0.4.4+build.18.jar
8. vector-addon-0.3.7.jar
```

**Comment by ThebestkillerTBK** [comment]
works for me, check seed setting

**Comment by 19MisterX98** [comment]
some servers change ore generation. You should try to compare ore gen between the server and a singleplayer world with the same seed and mc version

**Comment by Aholicknight** [comment]
> some servers change ore generation. 

@19MisterX98 If this is the case is there any way to bypass this? `.ghost` sometimes work but I have to be near the ores to load. Thank you for your help.

**Comment by 19MisterX98** [comment]
ghost/aax is the only other thing that i know

**Comment by Aholicknight** [comment]
> ghost/aax is the only other thing that i know 

@19MisterX98 While it does work, (you have to be near the obfuscated ore for it to fully load) would blocking any of the packets help with this or am I SOL? Thanks for your help again and merry christmas

**Comment by Aholicknight** [comment]
Let me run `.server plugins` and show what plugins they have currently installed.

**Comment by Aholicknight** [comment]
![image](https://user-images.githubusercontent.com/7843719/209446926-3071fbcc-4525-4504-bbba-107948b8726e.png)

**Comment by 19MisterX98** [comment]
I doubt that theres a bypass for the server blocking your ghost packets.

**Comment by Aholicknight** [comment]
I see. Well thank you for the help.

**Comment by optimizeee** [comment]
i think u didnt put it to the correct version cuz at bypasses any antixray plugin, infact that is what is it made for... the problem is maybe you chose the wrong version or the server was created in some other version and then updated and those chunks from the previous version remained intact.. that could be the only reason.. cuz it does bug sometimes and not show the correct place, but i think it is mainly due to it not supporting the version like i chose 1.21 and th server is 1.21.4.. even though they should have the same seed. But some few placements may be changed @19MisterX98  do you think this is the problem?

**Comment by 19MisterX98** [comment]
The issue is closed since 2 years. Get a life...
