### ISSUE TITLE
[Suggestion] Killaura random teleport (TP aura)

### ISSUE THREAD

**Issue by Squidom** [AntiCope/meteor-rejects#220]
### Describe the feature

It was removed (https://github.com/MeteorDevelopment/meteor-client/commit/8722ef565afa02ca4b6d9710a20fc9fcfd97bf05) from Meteor and since it will not be added back it makes sense to be added in meteor-rejects.

https://github.com/MeteorDevelopment/meteor-client/issues/3300

**Comment by ThebestkillerTBK** [comment]
#221
