### ISSUE TITLE
Remove meteor client keybinds from controls menu

### ISSUE THREAD

**Issue by EnvisagedMyron** [AntiCope/meteor-rejects#230]
### Describe the feature

it's really easy to catch someone using meteor by just telling them to go into their controls menu while screensharing , this feature could be really useful  for getting away with using meteor client lol

**Comment by I-Got-You-Dead2** [comment]
Dont

**Comment by I-Got-You-Dead2** [comment]
Use

**Comment by I-Got-You-Dead2** [comment]
Meteor

**Comment by I-Got-You-Dead2** [comment]
Where

**Comment by I-Got-You-Dead2** [comment]
Its

**Comment by I-Got-You-Dead2** [comment]
Not

**Comment by I-Got-You-Dead2** [comment]
Allowed

**Comment by C10udburst** [comment]
<img src="https://cdn.discordapp.com/emojis/973302190670249984.gif?size=48&quality=lossless" alt=":diesfromcringe:">

**Comment by EnvisagedMyron** [comment]
> Allowed

why is there anti vanish then?

**Comment by I-Got-You-Dead2** [comment]
> > Allowed
> 
> why is there anti vanish then?

Why not
