### ISSUE TITLE
Ore sim doesn't work

### ISSUE THREAD

**Issue by DermitKess** [AntiCope/meteor-rejects#235]
### Describe the feature

I can't type seed in Ore Sim, how I can fix it?

**Comment by C10udburst** [comment]
To use Ore Sim or .locate seed features you need to firstly set the seed using .seed <seed> <version> command.
Rejects doesn't have any seed cracking features, but you can use it with SeedCrackerX. You can download it here:
https://github.com/19MisterX98/SeedcrackerX
You can also visit SeedcrackerX discord server if you have any issues:
https://discord.gg/JRmHzqQYfp
