### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Cryptoisweird** [AntiCope/meteor-rejects#237]
### Describe the bug

whenever i try to load one of my minecraft servers with meteor rejects and meteor client the game says "Connection Lost, Internal exception: java.lang.nosuchmethoderror: 'void anticope.rejects.events.custompayloadevents.setcancelled(boolean) i have tried removing meteor rejects from my mods folder and when i do that my worlds work perfectly fine. idk what to do so can someone help me

### Crashlog

game does not crash

### Steps to reproduce

1. i add meteor rejects to mods folder and servers dont work

### Operating System

None

### Addon Version

1.19.4 Rejects version

### Meteor Version

1.19.4 Meteor version

### Minecraft Version

Fabric 1.19.4

### Other mods

```plaintext
1. i am using fabric api which is needed for the mods
```

**Comment by DawnCN** [comment]
me too

**Comment by jklmm7xw** [comment]
me too
