### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by anonymous9284** [AntiCope/meteor-rejects#238]
### Describe the bug

when i try to log in a sever it says internal Exception: java.lang.NosuchmethodError: 'void anti.cope.rejects.events.CustomplayloadEvent.set.Cancelled {boolean}

### Crashlog

 internal Exception: java.lang.NosuchmethodError: 'void anti.cope.rejects.events.CustomplayloadEvent.set.Cancelled {boolean}

### Steps to reproduce

1.
2.
3.
...
loading in a game

### Operating System

None

### Addon Version

0.2

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Other mods

```plaintext
1.
2.
3.
...
none but fabric api
```

**Comment by anonymous9284** [comment]
yeah or no

**Comment by BDARmech** [comment]
I apologize, but I don't see anything to track a bug here. You've posted a question to a bug that has been addressed.

**Comment by jklmm7xw** [comment]
> I apologize, but I don't see anything to track a bug here. You've posted a question to a bug that has been addressed.

what does that even mean did you use a translator
