### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Chestnutess** [AntiCope/meteor-rejects#239]
### Describe the bug

When I use meteor client and  meteor rejects load my world server it shows connection failure internal exception：java.lang.nosuchmethoderror：'void anticope.rejects.events.custompayloadevents.setcancelled(boolean)  I have tried removing meteor rejects and I can access the server normally

### Crashlog

No crashes occurred

### Steps to reproduce

1.Add meteor client and  meteor rejects to the mod folder
2.Start the game
3.Error connecting to the server
...

### Operating System

Windows

### Addon Version

1.19.4meteor rejects

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Other mods

```plaintext
1.i am using fabric api which is needed for the mods
2.
3.
...
```

**Comment by jklmm7xw** [comment]
same
