### ISSUE TITLE
[Suggestion] update to 1.20

### ISSUE THREAD

**Issue by NCPUser** [AntiCope/meteor-rejects#252]
### Describe the feature

please

**Comment by Meesterbouwer123** [comment]
meteor client needs to update first, but they are waiting for baritone to update

**Comment by ItzSkyReed** [comment]
Its been 1 day without meteor-client 1.20 jar, I can’t stop shaking and I’m having severe mental breakdowns. I had a major panic attack but managed to calm down after a few hours. I couldn’t go to school today, I am so worried. I am nothing without meteor-client 1.20, it is my life, it is my destiny, without meteor-client 1.20, I wouldn't be able to do anything. meteor-client 1.20 is the best thing ever made and I can't get rid of my addiction to it, it is the best client . I can't stop trembling and crying, I am very worried. I don't know what to do. meteor-client 1.20 can't be delayed for any longer cause if it does then I'll go insane again.. breaking my mouse, chair, house and everything I own is very amazing and I can't lose it. meteor-client 1.20 is my life, And the day after... 1.20 was released and I went through my panic attack, Shivering in fear. I am so scared that I might just lose my mind and go insane.


Its been 2 Days without meteor-client 1.20 jar, what I said yesterday happened.  I threw my mouse at the monitor.  Broke the keyboard on my leg.  Pulled the lamp from the ceiling.  I couldn't stop until I accidentally hit my head on a wardrobe that was falling on me.  While I was unconscious, I had a dream where meteor-client 1 20 jar was released.  I cried with happiness, I was ready to build a monument to the great meteor-client 1 20 jar.  Then everything suddenly stopped, I woke up.  Realized all the horror, meteor-client 1 20 jar has not been released for two days.  I.. It seems to me that I won't survive the third day... I.. I will burn down my house... Now I'm sitting and writing this from a friend's phone, before that I cried for 5 hours. I see his logo everywhere... On street advertisements, in pictures with cats.  I can't make out the text, I only see meteor-client 1 20 jar.  Help!  Release meteor-client 1 20 jar

**Comment by Weigurde** [comment]
okay guys we have 1.20 meteor let's go

**Comment by aRandomMenno** [comment]
No update to 1.20.1 it is already out for 2 days I think LOL. PWETTY PWETTY PWEASE>>

**Comment by Madesh-sudo** [comment]
1.20 is out, and even 1.20.1

When will this be updated to 1.20?

**Comment by I-Got-You-Dead2** [comment]
Fuck off cunt

**Comment by Emilia33** [comment]
still waiting for 1.20

**Comment by aRandomMenno** [comment]
It already update...
Use the latest dev build!

**Comment by FlightXamb** [comment]
> still waiting for 1.20

Cant you just wait, the developers are humans and have a life too.

**Comment by FlightXamb** [comment]
> literally just said they're waiting, no one said to rush it, we are all waiting.
Yea but like one suggestion is enough no need to come everyday and say "_still_ waiting for 1.20"

**Comment by RacoonDog** [comment]
i will personally update rejects when this thread stays inactive for over a day

**Comment by C10udburst** [comment]
:trollface:

**Comment by NCPUser** [comment]
wow
