### ISSUE TITLE
[Suggestion] update to 1.20.1

### ISSUE THREAD

**Issue by jklmm7xw** [AntiCope/meteor-rejects#257]
### Describe the feature

please

**Comment by bluepanee** [comment]
I made a dirty fork with 1.20-1.20.1 support. You can download it here:
https://github.com/bluepanee/meteor-rejects/releases/tag/0.3

**Comment by ManInMyVan** [comment]
The 1.20 version works on 1.20.1 too

**Comment by ManInMyVan** [comment]
It got updated to say 1.20.1, please close
