### ISSUE TITLE
[Suggestion] oresim generate-random-seeds-for-all mode

### ISSUE THREAD

**Issue by erxson** [AntiCope/meteor-rejects#264]
### Describe the feature

ore_diamond_buried + ore_diamond_large + ore_diamond_small + fossil_diamonds
ore_ancient_debris_large + ore_ancient_debris_small etc.
I do not know how it is convenient to use, but maybe you will have some idea.

**Comment by 19MisterX98** [comment]
This feature would only be useful if the user knows the ore seeds....
Something thats highly unlikely...

Conclusion: Its not worth the effort

**Comment by erxson** [comment]
Got it, thank you
