### ISSUE TITLE
latest release doesn't work with seedcracker x

### ISSUE THREAD

**Issue by mathmakgakpak** [AntiCope/meteor-rejects#31]
Latest release doesn't work with [seed cracker x](https://github.com/19MisterX98/SeedcrackerX). It still works with it in the one before build

**Comment by mathmakgakpak** [comment]
[crash-2021-08-13_13.17.13-client.txt](https://github.com/AntiCope/meteor-rejects/files/6982047/crash-2021-08-13_13.17.13-client.txt)
crash report

**Comment by C10udburst** [comment]
that is because seed cracker x uses old version of [hube12:SEED](https://github.com/hube12/SEED). i will try fixing it on my end.

**Comment by mathmakgakpak** [comment]
thanks
