### ISSUE TITLE
[Suggestion] Update to 1.20.4

### ISSUE THREAD

**Issue by notthatdudefr** [AntiCope/meteor-rejects#315]
### Describe the feature

update to 1.20.4 please

**Comment by pargivaht** [comment]
Agreed.

**Comment by Anonimouze** [comment]
Agreed.

**Comment by codespaces-minecraft** [comment]
until someone makes a pull to actually do it properly, you can just edit the `fabric.mod.json` to not require 1.20.2 and it works fine

**Comment by Oogaboogaman21** [comment]
> Agreed.

Thank you
