### ISSUE TITLE
[Bug]: Locate does not work on v1_18 and above (Workaround included)

### ISSUE THREAD

**Issue by gptlang** [AntiCope/meteor-rejects#316]
### Describe the bug

https://github.com/AntiCope/meteor-rejects/blob/bf6f7c5e648112d0e180c8306f37e1d1f5d72c5b/src/main/java/anticope/rejects/utils/WorldGenUtils.java#L235-L237

The code is disabled for v1_18 and above because it gives wrong coordinates. This is because [mc_biome_java](https://github.com/SeedFinding/mc_biome_java) is somewhat abandoned.

I got it working again (Linux only) by replacing the dependency with [cubiomes](https://github.com/Cubitect/cubiomes) via [C to Java bindings](https://github.com/acheong08/cubiomes). It's still work in progress for locating strongholds. I am not a Java nor C programmer so I have no idea what I'm doing. This is my fork: https://github.com/gptlang/meteor-rejects (Build doesn't work properly because of GitHub maven package fuckery. Need to install dependencies manually)

I can do much of it myself. My current issues are:
- Setting up a workflow to compile the Linux/Windows/Darwin versions
- Getting the builds all nice and automated (How do I use maven?)

(This is my alt. Main is [here](https://github.com/acheong08))

This [release/build](https://github.com/gptlang/meteor-rejects/releases/tag/1.20.4) currently works on Linux for most features.

**Comment by gptlang** [comment]
Alternatively, if embedding C too much trouble, I also extracted the JavaScript and WebAssembly from Chunkbase into a proper NodeJS module you can use: https://github.com/gptlang/MC-SeedLocator It's quite a bit slower than cubiomes though but also works with stronghold. I don't know if it's easier or harder to embed that. Last ditch effort would using CGO and having it as an API which the Java calls over HTTP.

**Comment by acheong08** [comment]
![image](https://github.com/AntiCope/meteor-rejects/assets/36258159/c02bfbac-88d0-4fe6-bdaa-bcd1f8f83b0a)

So for stronghold, there is a slight difference but it's in the correct general area.
Most features get the exact position right.
Sometimes I calculate the distance slightly wrong & a different correct location shows up as closest rather than the actual closest one. Probably because I don't have access to the Y. Not much of an issue though since it works anyways

**Comment by RacoonDog** [comment]
> Sometimes I calculate the distance slightly wrong & a different correct location shows up as closest rather than the actual closest one. Probably because I don't have access to the Y. Not much of an issue though since it works anyways

Vanilla uses manhattan distance to find the nearest one

**Comment by acheong08** [comment]
> Vanilla uses manhattan distance to find the nearest one

No harm in being more accurate I guess.

Also, MacOS build succeeded (Same jar file). Once I get Windows support, I'll make a PR.

**Comment by gptlang** [comment]
Pull request open. If anyone is interested, please test on Windows and MacOS. I only have Linux but it *should* work
