### ISSUE TITLE
[Bug] new chunks crash

### ISSUE THREAD

**Issue by jklmm7xw** [AntiCope/meteor-rejects#322]
### Describe the bug

new chunks crashes the game and i cant rejoin the game with meteor rejects enabled because it will keep crashing

### Crashlog

no

### Steps to reproduce

1.turn on new chunks
2.the game crashes
3.
...

### Operating System

Windows

### Addon Version

latest

### Meteor Version

latest

### Minecraft Version

latest

### Other mods

```plaintext
1.
2.
3.
...
```

**Comment by 19MisterX98** [comment]
Attach a crash report to be taken seriously. Preferably use [mclogs](https://mclo.gs)
