### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mathmakgakpak** [AntiCope/meteor-rejects#39]
**Describe the bug**
Since [this](https://github.com/AntiCope/meteor-rejects/tree/fe4fd53b71d11510e5fa0185aa4c0a180a10bf55) commit tracers with skeleton esp are bugged while flying with elytra.

**To Reproduce**
1. Enable skeleton esp and tracers
2. fly with elytra
3. enable freecam

**Expected behavior**
make it normal again

**Screenshots**
![image](https://user-images.githubusercontent.com/44949126/130636778-95b1ee46-83e6-4309-8ebc-adebde28770a.png)

**Comment by C10udburst** [comment]
I need a bit more context.

Does this happen to fake players, other players or you?

**Comment by mathmakgakpak** [comment]
players that fly with elytra
