### ISSUE TITLE
[Suggestion] OreSim unavailable for 1.21.x

### ISSUE THREAD

**Issue by SMFDrummer** [AntiCope/meteor-rejects#393]
### Describe the feature

latest version 0.3 only until 1.20.4, how can I use .seed for 1.21/1.21.1 ?

**Comment by VisionFXC** [comment]
Yeah we need an update for that.

**Comment by SMFDrummer** [comment]
Someone in action had updated seedfinder implemetation version so oresim can be used on 1.21.0, I'll close this and waiting for new actions.

**Comment by XiaoGanCN** [comment]
https://github.com/XiaoGanCN/meteor-rejects/releases/tag/latest-1.21
tested on 1.21.3
