### ISSUE TITLE
[Suggestion] skid o-r-e-s-i-m from a-t-o-m-i-c

### ISSUE THREAD

**Issue by mathmakgakpak** [AntiCope/meteor-rejects#40]
[O-r-e-s-i-m](https://github.com/cornos/Atomic/tree/master/src/main/java/me/zeroX150/atomic/feature/module/impl/render/OreSim)

:trollface:

[My suggestion](https://github.com/MeteorDevelopment/meteor-client/issues/537) just chills as 17th oldest in meteor suggestions

EDIT: fixed ur markdown <img src="https://user-images.githubusercontent.com/18114966/130804847-3aa0654b-01e8-43e5-a623-eb6de4f45fd3.png" width="16px" alt=":briish:" title=":briish:">

**Comment by mathmakgakpak** [comment]
Sorry for question unrelated to suggestion but are you planning to do meteor rejects discord

**Comment by C10udburst** [comment]
If I get to making an ore sim module i doubt i'll use atomic code, as I already am using [hube12:SEED](https://github.com/hube12/SEED) for `.locate`.

> Sorry for question unrelated to suggestion but are you planning to do meteor rejects discord

I doubt it, noone likes moderating discord servers.

**Comment by mathmakgakpak** [comment]
ok then. thanks for response

**Comment by mathmakgakpak** [comment]
I found out you can do `/seedmapper:highlight block <ore>` using seedmapper but i still would want to see it

**Comment by C10udburst** [comment]
added in #101
