### ISSUE TITLE
[Suggestion] ImageESP

### ISSUE THREAD

**Issue by Cypphi** [AntiCope/meteor-rejects#42]
Display a picture of your own on any entity like normal ESP. Might as well suggest it here right away before snail starts coping and closing my suggestion.

(*Don't question it, I need my popbob and simon esp*)

**Comment by Cypphi** [comment]
> Not even speaking English at this point

Am I being Englishn't again? That seems pretty correct to me, just confusing to read...

**Comment by Cypphi** [comment]
What I basically mean is:
A module which renders an image (which you can import yourself) onto specific entities such as players. This would be so you could do bullshit like put a popbob head over a player (or use a good looking png to actually make a good looking esp)

**Comment by C10udburst** [comment]
added in MeteorDevelopment/meteor-client@2def9f9df583c4c108b653d8403746b39e0f5dd5 i think?

**Comment by RacoonDog** [comment]
> added in [MeteorDevelopment/meteor-client@2def9f9](https://github.com/MeteorDevelopment/meteor-client/commit/2def9f9df583c4c108b653d8403746b39e0f5dd5) i think?

that commit adds an option to replace the solid color chams with a single hardcoded texture, not something as customizable as was suggested here

**Comment by C10udburst** [comment]
have you heard about resource packs?

**Comment by RacoonDog** [comment]
its literally hardcoded

**Comment by MineGame159** [comment]
have you heard about resource packs?

**Comment by RacoonDog** [comment]
csnail literally just fixed it...

**Comment by MineGame159** [comment]
It worked with the first commit he did
