### ISSUE TITLE
Add cev breaker

### ISSUE THREAD

**Issue by CheFuls** [AntiCope/meteor-rejects#51]
### Describe the feature

Add cev breaker lol

**Comment by mathmakgakpak** [comment]
just use https://github.com/GhostTypes/orion with meteor rejects

**Comment by Raxii** [comment]
instamine is civ break

**Comment by mathmakgakpak** [comment]
i think that cevbreaker is other thing than civ breaker

**Comment by mathmakgakpak** [comment]
oh i thought about wrong module
