### ISSUE TITLE
Cope

### ISSUE THREAD

**Issue by CheFuls** [AntiCope/meteor-rejects#53]
### Describe the bug

Fix auto tnt

### Steps to reproduce

```bash
Bruuuuuuuuuhhhhh
```

### Operating System

Windows

### Meteor Version

0.4.5

### Minecraft Version

1.17

### Other mods

```bash
Meteor xd
```

**Comment by StormyBytes** [comment]
Duplicate of #37

**Comment by C10udburst** [comment]
> Steps to reproduce
> Bruuuuuuuuuhhhhh

mfw
