### ISSUE TITLE
[Bug] Painter performance issue

### ISSUE THREAD

**Issue by FeminineFemale** [AntiCope/meteor-rejects#59]
### Describe the bug

when I enable painter my fps goes to .5 literally and makes my game not respond but it does work

### Steps to reproduce

```bash
1.enable painter
2.experience lag
3.
...
```

### Operating System

Windows

### Meteor Version

Dev build 1250

### Minecraft Version

1.17.1

### Other mods

```bash
1. Alto Chef (a mod that uses baritone to beat the game and automatically get items starting out with nothing)
2. Baritone (custom baritone fork for alto chelf
3. Auto bedrock Miner 1.17.1
4. Duper trooper and 0x150s shulker dupe mod
5. Seed Cracker fork for 1.17
6. Sodium
7. Lithium
8. Meteor Client
9. Fabric API
```

**Comment by StormyBytes** [comment]
I am unsure as to how should Painter be optimized. 
If anyone can come up with an optimized version of it, feel free to open a pull request for it.

For the meantime, the only solution I can think off is try increasing the delay for placement.

**Comment by NoobMaster420-69** [comment]
https://discord.gg/JURmqYCZ discord invite github is https://github.com/gaucho-matrero/altoclef
