### ISSUE TITLE
Phase is skidded as u know

### ISSUE THREAD

**Issue by CheFuls** [AntiCope/meteor-rejects#82]
### Describe the bug

D u know that NRNB mode in phase are not just random name? This is name of server where this phase was invented for. And this mode was leaked from Bedtrap 0.3.1 as you actualy know. NIGGY

### Steps to reproduce

```plaintext
requires brain
```

### Operating System

Windows

### Rejects Version

last

### Meteor Version

Last devbuild

### Minecraft Version

1.17.1

### Other mods

```plaintext
Look WITH EYES that u dont have
```

**Comment by CheFuls** [comment]
U are not managed to fucking rename it? Wtf is wrong with you?

**Comment by CheFuls** [comment]
And i wanna add one thing. GIVE LEAKED BEDTRAP THE HEACKIN CREDITS FOR UR SHAME FOR NOT ADDING IT IN TIME.

**Comment by Errorcrafter** [comment]
🥱

**Comment by Epik123** [comment]
> And i wanna add one thing. GIVE LEAKED BEDTRAP THE HEACKIN CREDITS FOR UR SHAME FOR NOT ADDING IT IN TIME.

why would someone give credit to a leak kys nn

**Comment by SWP360** [comment]
who gives a shit lmaoooo
