### ISSUE TITLE
[Suggestion] update to 1.18

### ISSUE THREAD

**Issue by snnwer** [AntiCope/meteor-rejects#84]
### Describe the feature

title

**Comment by StormyBytes** [comment]
Use eyes
https://github.com/AntiCope/meteor-rejects/compare/32232a8aa91b6cbf2438150f755c2f7655756558...82c863fce71f193435703e6812b46e275a4cccb9
Rejects is already 1.18

**Comment by snnwer** [comment]
> Use eyes [32232a8...82c863f](https://github.com/AntiCope/meteor-rejects/compare/32232a8aa91b6cbf2438150f755c2f7655756558...82c863fce71f193435703e6812b46e275a4cccb9) Rejects is already 1.18

yeah im retarded sorry only figured it out
