### ISSUE TITLE
AntiVanish searchs PlayerID from UUID but...

### ISSUE THREAD

**Issue by Pillowmen** [AntiCope/meteor-rejects#86]
### Describe the feature

I had always played in "offline servers" wich means it accepts player that doesn't own Minecraft account, so that means when the antivanish try search PlayerID from UUID it doesn't show up.
I doesn't show any notification when an player enter into the server and writes /vanish.

Could you fix this,
Thanks

**Comment by C10udburst** [comment]
it returns the uuid if the username check fails. there is no way to get the username from uuid on offline servers when vanished
