### ISSUE TITLE
[Bug] Crash when cancelling the open skin file dialog

### ISSUE THREAD

**Issue by SIMULATAN** [AntiCope/meteor-rejects#87]
### Describe the bug

When typing `.skin` into the chat and closing the GUI, the game crashes because the path to the file is null.

### Steps to reproduce

```plaintext
1. Type `.skin`
2. Click "cancel" in the file picker GUI
```

### Operating System

Windows

### Rejects Version

latest-1.18
095999c

### Meteor Version

0.4.7-1373

### Minecraft Version

1.18.1

### Other mods

```plaintext
Not required (I suppose)
```

**Comment by SIMULATAN** [comment]
I hope this is the right repo now 😅

**Comment by C10udburst** [comment]
There is a null check [in place](https://github.com/AntiCope/meteor-rejects/blob/82c863fce71f193435703e6812b46e275a4cccb9/src/main/java/anticope/rejects/commands/SaveSkinCommand.java#L49).

Can you send the crash log?

**Comment by SIMULATAN** [comment]
https://gist.github.com/SIMULATAN/1a9475f9b5bb3f6f1be7a4972434ef43

**Comment by SIMULATAN** [comment]
I just checked it and the commit of the build is **after** the last commit of the file so I should have the fix in place.
I'll decompile the mod rq and check if its there

**Comment by SIMULATAN** [comment]
Wait, what if the #create method throws the exception but the overlaying methods don't catch this exception?
After all, it says "reported exception thrown" in the logs...
