### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Spinyfish** [AntiCope/meteor-rejects#89]
### Describe the bug

Enabling packet fly will just instantly crash your MC

### Steps to reproduce

```plaintext
1. enable packet fly while in a singeplayer world or server.
2.
3.
...
```

### Operating System

Windows

### Rejects Version

Newest (currently)

### Meteor Version

dev Build 1362

### Minecraft Version

1.18

### Other mods

```plaintext
1. Litematica
2.
3.
...
```

**Comment by C10udburst** [comment]
can you send the crash log?

**Comment by Spinyfish** [comment]
[crash-2021-12-29_12.39.56-client.txt](https://github.com/AntiCope/meteor-rejects/files/7790854/crash-2021-12-29_12.39.56-client.txt)
