### ISSUE TITLE
[Bug] Meteor's way of HUD recently change, likely causes crash on startup

### ISSUE THREAD

**Issue by Bneboy** [AntiCope/meteor-rejects#92]
### Describe the bug

Hey so I had downloaded the latest version of the dev build, and the latest version of rejects, and the game crashes at startup.
Looking at the dev logs, it says they (very) recently removed HUD module and moved it to a HUD tab.

The crash log has to do with something involving the HUD, so I assume they are related
Crash log: https://pastebin.com/MTrSRctM

Again this is a very recent change on a dev build, so they might revert back, might not. Just thought I'd post it here just in case

### Steps to reproduce

```plaintext
1. Install both meteor latest dev build & rejects version
2. Launch game
```

### Operating System

Windows

### Rejects Version

b1fa434a9c25d75b2a4b92adb374d8e3f044c673

### Meteor Version

0.4.7-1388

### Minecraft Version

1.18.1

### Other mods

```plaintext
none
```

**Comment by SIMULATAN** [comment]
Can confirm

**Comment by SIMULATAN** [comment]
Should be fixable by changing https://github.com/AntiCope/meteor-rejects/blob/master/src/main/java/anticope/rejects/MeteorRejectsAddon.java#L90 to `HUD hud = Systems.get(HUD.class)`

Source: https://github.com/MeteorDevelopment/meteor-client/commit/bb888452b41bf1bd009669e637d9257ab39bd4c2#diff-bfcde3c873d218821475d7c02e2cc2f187650c19851ad672b58a15d60601992fR75

Unfortunately i'm too dumb to setup the workspace rn (got issues with the discord rpc not beeing found by gradle) so i can't test this but it should be bullet proof

**Comment by BookWyrm114** [comment]
I have this same issue

**Comment by energy11a** [comment]
The issue exists with meteor dev 1380 and latest meteor-rejects.

**Comment by SIMULATAN** [comment]
There's already a [PR Open](https://github.com/AntiCope/meteor-rejects/pull/93) but it hasn't been merged yet

A working build can be downloaded [here](https://github.com/AntiCope/meteor-rejects/suites/4853900186/artifacts/137926384)

@BookWyrm114 @energy11a @Bneboy
