### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by robbieW2004** [AntiCope/meteor-rejects#94]
### Describe the bug

When starting Minecraft it crashes with errorcode 0 or 

The game crashed whilst initializing game
Error: java.lang.NoSuchFieldError: settings
Afsluitcode: -1
full crash log provided below
[crash-2022-01-07_20.34.21-client.txt](https://github.com/AntiCope/meteor-rejects/files/7830952/crash-2022-01-07_20.34.21-client.txt)

### Steps to reproduce

```plaintext
1. Start minecraft as usual
2.
3.
...
```

### Operating System

Windows

### Rejects Version

latest build

### Meteor Version

latest dev and 4.6

### Minecraft Version

1.18.x tested both

### Other mods

```plaintext
1. i tested with other mods and just meteor, meteor rejets and fabric api
2.
3.
...
```

**Comment by SIMULATAN** [comment]
now thats weird

**Comment by C10udburst** [comment]
you're using old version of meteor.

use [the newest dev build](https://meteorclient.com/download?devBuild=latest)

**Comment by SIMULATAN** [comment]
now thats not weird anymore
